version: '3'
services:
  redis:
    image: redis:5

  mysql:
    image: mysql:5.7
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    environment:
      - MYSQL_ROOT_PASSWORD=test
      - MYSQL_DATABASE=n0bbs
    volumes:
      - ./var/mysql:/var/lib/mysql

  ui:
    image: node:13
    command: yarn start
    working_dir: /srv
    volumes:
      - ./ui:/srv

  app:
    build:
      context: ./src
      dockerfile: Dockerfile
    command: python manage.py runserver 0.0.0.0:8000
    environment:
      SECRET_KEY: "hogehoge"
      DEBUG: "true"
      ALLOWED_HOST: localhost
      SLACK_INCOMING_HOOK_URL:
      SOCIAL_AUTH_GITHUB_KEY:
      SOCIAL_AUTH_GITHUB_SECRET:
    ports:
      - "8000:8000"
    volumes:
      - ./src:/srv
    links:
      - mysql
      - redis

  nginx:
    image: nginx
    volumes:
      - ./etc/nginx/conf.d/:/etc/nginx/conf.d
      - ./src/static:/usr/share/nginx/html/api/static
    ports:
      - "8000:80"
    links:
      - app
      - ui
