version: '3.7'
services:
  redis:
    image: redis:5

  mysql:
    image: mysql:5.7
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=n0bbs
    volumes:
      - ../var/mysql:/var/lib/mysql

  app:
    build:
      context: ../
      dockerfile: Dockerfile
      target: APP
    environment:
      DEBUG: "false"
      SECRET_KEY:
      ALLOWED_HOST:
      SLACK_INCOMING_HOOK_URL:
      SOCIAL_AUTH_GITHUB_KEY:
      SOCIAL_AUTH_GITHUB_SECRET:
    links:
      - mysql
      - redis

  nginx:
    build:
      context: ../
      dockerfile: Dockerfile
    ports:
      - "8000:80"
    links:
      - app
