# Generated by Django 3.0.4 on 2020-03-06 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bbs', '0004_auto_20200306_0414'),
    ]

    operations = [
        migrations.AddField(
            model_name='response',
            name='display_name',
            field=models.CharField(default='n0nameさん', max_length=65, verbose_name='ハンドルネーム'),
        ),
    ]
