# Generated by Django 3.0.4 on 2020-03-06 12:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bbs', '0006_auto_20200306_1524'),
    ]

    operations = [
        migrations.AlterField(
            model_name='readlog',
            name='response',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='bbs.Response'),
        ),
    ]
