# Generated by Django 3.0.4 on 2020-03-05 19:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bbs', '0003_auto_20200306_0201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='response',
            name='comment',
            field=models.TextField(max_length=4095, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='response',
            name='thread',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='bbs.Thread'),
        ),
        migrations.CreateModel(
            name='ReadLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('response', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bbs.Response')),
                ('thread', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bbs.Thread')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
