# Generated by Django 3.0.4 on 2020-03-06 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bbs', '0005_response_display_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='thread',
            name='anonymous',
            field=models.BooleanField(default=False, verbose_name='匿名スレ'),
        ),
        migrations.AlterField(
            model_name='response',
            name='display_name',
            field=models.CharField(default='n0nameさん', max_length=65, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='thread',
            name='title',
            field=models.CharField(max_length=255, verbose_name='スレタイ'),
        ),
    ]
