# Generated by Django 3.0.4 on 2020-03-10 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bbs', '0008_auto_20200306_2225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thread',
            name='title',
            field=models.CharField(max_length=255, unique=True, verbose_name='スレタイ'),
        ),
    ]
