# Generated by Django 3.0.4 on 2020-03-10 07:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bbs', '0009_auto_20200310_1633'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='thread',
            name='archived_at',
        ),
    ]
