# Generated by Django 3.0.4 on 2020-03-13 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bbs', '0012_auto_20200313_2255'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='user',
            new_name='author',
        ),
    ]
