# Generated by Django 3.0.4 on 2020-03-14 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bbs', '0014_channel_channelrelation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channel',
            name='name',
            field=models.CharField(max_length=32, unique=True),
        ),
    ]
