# Generated by Django 3.0.4 on 2020-03-14 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bbs', '0015_auto_20200314_1642'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channelrelation',
            name='states',
            field=models.IntegerField(choices=[(0, 'INVITED'), (1, 'JOINED'), (2, 'MUTED')], default=0),
        ),
    ]
