# Generated by Django 3.0.4 on 2020-03-14 08:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bbs', '0016_auto_20200314_1652'),
    ]

    operations = [
        migrations.RenameField(
            model_name='channelrelation',
            old_name='states',
            new_name='state',
        ),
    ]
