# Generated by Django 3.0.4 on 2020-03-14 09:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bbs', '0019_auto_20200314_1746'),
    ]

    operations = [
        migrations.AddField(
            model_name='thread',
            name='channel',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='threads', to='bbs.Channel'),
        ),
    ]
