# Generated by Django 3.0.4 on 2020-03-14 15:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bbs', '0020_thread_channel'),
    ]

    operations = [
        migrations.AddField(
            model_name='channel',
            name='users',
            field=models.ManyToManyField(related_name='channels', through='bbs.ChannelRelation', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='channelrelation',
            name='channel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bbs.Channel'),
        ),
        migrations.AlterField(
            model_name='channelrelation',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
